# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-test
plugins:
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    ADM_AUTH_TOKEN: ${{ env:ADM_AUTH_TOKEN }}
    BASIC_AUTH_TOKEN: ${{ env:BASIC_AUTH_TOKEN }}
    BFF_MAINTENANCE: ${{ env:BFF_MAINTENANCE }}
    MAXIMUM_CAPACITY_WEBVIEW_CHAVE: ${{ env:MAXIMUM_CAPACITY_WEBVIEW_CHAVE }}
    MAXIMUM_CAPACITY_WEBVIEW_URL: ${{ env:MAXIMUM_CAPACITY_WEBVIEW_URL }}
    MAXIMUM_CAPACITY_WEBVIEW_URL_RESPONSE: ${{ env:MAXIMUM_CAPACITY_WEBVIEW_URL_RESPONSE }}
    CHALLENGE_BASIC_AUTH_PASSWORD: ${{ env:CHALLENGE_BASIC_AUTH_PASSWORD }}
    CHALLENGE_BASIC_AUTH_USER: ${{ env:CHALLENGE_BASIC_AUTH_USER }}
    DB_HOST: ${{ env:DB_HOST }}
    DB_PASSWORD: ${{ env:DB_PASSWORD }}
    DB_POOL_INCREMENT: ${{ env:DB_POOL_INCREMENT }}
    DB_POOL_MAX: ${{ env:DB_POOL_MAX }}
    DB_POOL_MIN: ${{ env:DB_POOL_MIN }}
    DB_POOL_TIMEOUT: ${{ env:DB_POOL_TIMEOUT }}
    DB_PORT: ${{ env:DB_PORT }}
    DB_QUEUE_TIMEOUT: ${{ env:DB_QUEUE_TIMEOUT }}
    DB_SCHEMA: ${{ env:DB_SCHEMA }}
    DB_SID: ${{ env:DB_SID }}
    DB_URL: ${{ env:DB_URL }}
    DB_USER: ${{ env:DB_USER }}
    FIREBASE_CLIENT_EMAIL: ${{ env:FIREBASE_CLIENT_EMAIL }}
    FIREBASE_PRIVATE_KEY: ${{ env:FIREBASE_PRIVATE_KEY }}
    FIREBASE_PROJECT_ID: ${{ env:FIREBASE_PROJECT_ID }}
    HASH_PORTAL_CONFERENCIA: ${{ env:HASH_PORTAL_CONFERENCIA }}
    PREMMIA_PASSWORD: ${{ env:PREMMIA_PASSWORD }}
    PREMMIA_USERNAME: ${{ env:PREMMIA_USERNAME }}
    SSO_ADM_TOKEN: ${{ env:SSO_ADM_TOKEN }}
    SSO_VERIFY_TOKEN: ${{ env:SSO_VERIFY_TOKEN }}
    URL_PREMIA: ${{ env:URL_PREMIA }}
    URL_SSO_DELETE: ${{ env:URL_SSO_DELETE }}
    URL_SSO_SIGNUP: ${{ env:URL_SSO_SIGNUP }}
    URL_SSO_VERIFY: ${{ env:URL_SSO_VERIFY }}
    URL_WEBVIEW_PORTAL_CONFERENCIA: ${{ env:URL_WEBVIEW_PORTAL_CONFERENCIA }}
    ZOOM_ACCESS_TOKEN: ${{ env:ZOOM_ACCESS_TOKEN }}
    BFF_LOGOUT: ${{ env:BFF_LOGOUT }}
    APP_DESAFIO_AUTH_USER: ${{ env:APP_DESAFIO_AUTH_USER }}
    APP_DESAFIO_AUTH_SECRET: ${{ env:APP_DESAFIO_AUTH_SECRET }}
    APP_PORTAL_CONFERENCIA_DOMAIN: ${{ env:APP_PORTAL_CONFERENCIA_DOMAIN }}
    APP_PORTAL_CONFERENCIA_PATH: ${{ env:APP_PORTAL_CONFERENCIA_PATH }}
    APP_PORTAL_CONFERENCIA_COOKIE_NAME: ${{ env:APP_PORTAL_CONFERENCIA_COOKIE_NAME }}
    BIG_QUERY_PROJECT_CD_ID: ${{ env:BIG_QUERY_PROJECT_CD_ID }}
    BIG_QUERY_PRIVATE_KEY: ${{ env:BIG_QUERY_PRIVATE_KEY }}
    BIG_QUERY_CLIENT_EMAIL: ${{ env:BIG_QUERY_CLIENT_EMAIL }}
    BIG_QUERY_LOCATION: ${{ env:BIG_QUERY_LOCATION }}
    BORA_ENVIRONMENT: ${{ env:BORA_ENVIRONMENT }}

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello
          method: get

  sum:
    handler: handler.sum
    events:
      - http:
          path: sum
          method: get

  currentTime:
    handler: handler.currentTime
    events:
      - http:
          path: time
          method: get



