# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-test
plugins:
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    ENV1: ${env:ENV1}
    ENV2: ${env:ENV2}
    HOST: ${env:HOST}
    PORT: ${env:PORT}
    DATABASE_URL: ${env:DATABASE_URL}
    API_KEY: ${env:API_KEY}

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello
          method: get

  sum:
    handler: handler.sum
    events:
      - http:
          path: sum
          method: get

  currentTime:
    handler: handler.currentTime
    events:
      - http:
          path: time
          method: get