name: Continuous Deployment to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file from secret
      env:
        TEST_SECRET_ENV: ${{ secrets.TEST_ENV_DEV }}
      run: |
        # Define o arquivo .env
        env_file=".env"
        touch $env_file

        # Lê o conteúdo do segredo TEST_SECRET_ENV e grava no arquivo .env
        echo "$TEST_SECRET_ENV" | while IFS=': ' read -r key value; do
          key=$(echo $key | xargs)  # Remove espaços em torno da chave
          value=$(echo $value | xargs | sed 's/^"//;s/"$//')  # Remove espaços e aspas em torno do valor
          echo "$key=$value" >> $env_file
        done

        # Exibe o conteúdo do arquivo .env para verificação
        cat $env_file
    - run: npm ci
    - name: Serverless Deploy in AWS
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROHEM }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROHEM}}
      run: |
        npm i -g serverless@3.x
        serverless deploy --stage dev