name: Continuous Deployment to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load and parse environment variables from YAML secret
      env:
        ENV_VARS_YAML: ${{ secrets.ENV_VARS_YML_DEV }}
      run: |
        echo "$ENV_VARS_YAML" > env_vars.yml
        while IFS=': ' read -r key value; do
          echo "Setting $key=$value in .env file"
          echo "$key=$value" >> .env
        done < env_vars.yml

    - name: Print .env file content
      run: |
        cat .env
    - name: List directory contents
      run: |
        ls -al
    - run: npm ci
    - name: Serverless Deploy in AWS
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROHEM }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROHEM}}
      run: |
        npm i -g serverless@3.x
        serverless deploy --stage dev