name: Continuous Deployment to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print secret content for debugging
      run: echo "${{ secrets.ENV_VARS_JSON }}"

    - name: Save secret content to JSON file
      run: echo "${{ secrets.ENV_VARS_JSON }}" > env_vars.json

    - name: Print content of env_vars.json
      run: cat env_vars.json

    - name: Load environment variables from JSON
      id: load-env
      run: |
        cat env_vars.json | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' >> $GITHUB_ENV || echo "Failed to load environment variables"

    - name:  Print loaded environment variables
      run: |
        echo "Loaded environment variables:"
        cat $GITHUB_ENV

    - name: Print last 5 environment variables
      run: |
        tail -n 5 $GITHUB_ENV
    - run: npm ci
    # - name: serverless deploy
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: deploy
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROHEM }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROHEM }}