name: Continuous Deployment to AWS Lambda

on:
  push:
    branches:
      - main  # ajuste de acordo com a sua branch principal
  workflow_dispatch:  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci  # ou `npm install` dependendo da sua configuração

    - name: Create function.zip
      run: zip -r function.zip . -x "node_modules/*" ".git/*"

    - name: Upload function.zip as artifact
      uses: actions/upload-artifact@v2
      with:
        name: function-zip
        path: function.zip

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    needs: build  # O deploy depende do passo de build

    steps:
    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_ROHEM }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_ROHEM }}
        aws configure set default.region us-east-1  # ajuste para a sua região

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name my-test-function \
          --zip-file fileb://function.zip